name: Infra
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      CDK_DEBUG: "true"
      JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Debug refs
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-infra-${{ github.run_id }}
          aws-region: us-west-2

      - name: Who am I?
        id: whoami
        run: aws sts get-caller-identity

      - name: Install root deps
        run: npm ci --workspaces=false

      - name: Install infra deps (+ ensure esbuild)
        run: |
          cd infra
          npm ci
          npx esbuild --version || (npm i -D esbuild && npx esbuild --version)

      # 1) always run doctor/list; keep going even if they fail, and save logs
      - name: CDK doctor & list
        continue-on-error: true
        run: |
          cd infra
          {
            echo "=== cdk doctor ==="
            npx cdk doctor
            echo "=== cdk list -v ==="
            npx cdk list -v
          } | tee ../cdk_preflight.log

      # 2) ALWAYS bootstrap in CI (it's idempotent) so deploy won't fail for missing toolkit
      - name: CDK bootstrap (idempotent)
        run: |
          cd infra
          npx cdk bootstrap aws://167053021813/us-west-2 -v | tee ../cdk_bootstrap.log

      # 3) synth with verbose logging
      - name: CDK synth (verbose)
        run: |
          cd infra
          npx cdk synth -v | tee ../cdk_synth.log

      # 4) deploy with verbose logging
      - name: CDK deploy (verbose)
        run: |
          cd infra
          npx cdk deploy WebStack ApiStack ObservabilityStack --require-approval never -v | tee ../cdk_deploy.log

      # 5) always upload logs so we can see the real error, even on failure
      - name: Upload CDK logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cdk-logs
          path: |
            cdk_preflight.log
            cdk_bootstrap.log
            cdk_synth.log
            cdk_deploy.log
