name: Lighthouse
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # weekly
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://da.nielyi.com
          uploadArtifacts: true
          temporaryPublicStorage: true

